### ISSUE TITLE
Card damage amount is not read when the game language is set to Japanese

### ISSUE THREAD

**Issue by yncat** [bradjrenshaw/say-the-spire#8]
Here is what I've found so far.
I'm not familiar with Java standard libraries, but in here,
https://github.com/bradjrenshaw/say-the-spire/blob/8c4894d11a0e861ce4d264aeea277a4a1497659e/src/main/java/sayTheSpire/TextParser.java#L99
Reading through the code after this, I'm assuming that s.next() is scanning word by word. And when substituting dynamic variables, TextParser searches for a certain symbol and replaces it with the associated dynamic value.

I haven't tested this yet, but the scanner (instance s) might be separating simbol to replace incorrectly because Japanese doesn't have white spaces which scanner uses for the separation point.

**Comment by yncat** [comment]
I was able to setup my own development environment. I've found that the variables to substitute are not enclosed by ! signs, when the game language is set to Japanese. Sometimes it completely lacks ! at the both sides, and sometimes two ! signs are added at the right side E.G. b!! block.

**Comment by bradjrenshaw** [comment]
I believe I fixed this as of the latest commits to the beta2 branch. If you are able to compile and test the mod could you let me know if this is working correctly on your system?

**Comment by yncat** [comment]
Thank you very much for this!
I've looked through the diff and found out that you rewrote the parsing logic using rawDescription rather than DescriptionLine arrays. I knew that the original card object had some issues with ! escaping, so I would have taken the same approach as you did. It's not an easy fix I can definitely say. I really appreciate what you've done.
I'm going to close this issue after testing that it works on my computer.

**Comment by yncat** [comment]
@bradjrenshaw 
I compiled the latest code on beta2 branch and ran the game. After the startup, as soon as I press a down button, it infinitely scrolls down the menu cursor. I tried reverting to the latest master and it stopped occurring.
Do I have to perform something to make the latest beta work, EG. deleting the setting file or controller mapping?
I'm using an xbox controller with USB.

**Comment by bradjrenshaw** [comment]
@yncat sorry for the delay on this, I think I fixed it as of the latest commit to beta2. Can you please test it and let me know if that fixed it?

**Comment by yncat** [comment]
@bradjrenshaw 
Thank you for the fix. My controller now works!!!!!!!
I've tested the latest beta. Your fix has solved most of the issue though, I've found a special case where the parsing still fails. I quickly fixed it, tested that it works and sent a pull request. Would you mind reviewing #9 and see if the change is acceptable?

**Comment by bradjrenshaw** [comment]
@yncat thanks for that pull request, I merged it and everything looks fine. Have you encountered any other problems or do you think it's safe to close the issue?

**Comment by yncat** [comment]
I played the game three times with the latest beta. Currently there's no problem. I think this issue is safe to close. Thanks!
